[package]
name = "glutin_simple1"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0 OR BSD-3-Clause OR CC0-1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gl = "0.14"
glutin = "0.28"
winit = "0.28"
